name: Build mpv binary (without Docker)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang yasm git meson ninja-build \
             autoconf automake libtool pkg-config libfreetype6-dev libfribidi-dev \
             libfontconfig1-dev libasound2-dev pulseaudio libx11-dev libvdpau-dev \
             libgl-dev libxv-dev libjpeg-dev libssl-dev libx264-dev libmp3lame-dev 
             libfdk-aac-dev

    - name: Build mpv binary
      run: |
        ./rebuild -j4

    - name: Verify mpv binary
      run: |
        ./mpv/build/mpv --version

